### ISSUE TITLE
Iniciar un Servidor basico usando NodeJS.

### ISSUE THREAD

**Issue by pombodaniel10** [SemardUDC/Server-SEMARD#1]

**Comment by srhenals** [comment]
Done, instalé el NodeJS desde la página original y Visual Studio escribí el siguiente código:

`// Activating the NodeJS module
var http = require('http');

function onRequest(request, response) {
    console.log("A user made a request" + request.url); //Request.url allows me to know what is the user requesting
    response.writeHead(200, { "Context-Type": "text/plain" }); //The code and the kind of data we are sending back
    response.write("Here is some data"); //This is going to be printed on the user's screen throught the browser
    response.end();
}

http.createServer(onRequest).listen(8888);
console.log("The NodeJS's server is now running...")`

Una vez lo ejecuté lo probé en el navegador y funcionaba perfectamente.

**Comment by pombodaniel10** [comment]
Subelo al repositorio.

**Comment by pombodaniel10** [comment]
Investiga acerca de ExpressJS @Litem1

**Comment by srhenals** [comment]
Done, ya investigo al respecto.
